### ISSUE TITLE
tamedp error

### ISSUE THREAD

**Issue by BBetz907** [USAID-OHA-SI/tameDP#16]
When I run the following lines, an error occurs:

df_dp <- tame_dp(filepath, type = "PSNUxIM", map_names = TRUE) %>% glimpse()

Error: Can't join on `x$numeratordenom` x `y$numeratordenom` because of incompatible types.
i `x$numeratordenom` is of type <logical>>.
i `y$numeratordenom` is of type <character>>.

Do you know the reason for this? How would I resolve?

**Comment by achafetz** [comment]
When there is no PSNUxIM tab, the data types end up being logicals and do not match the disagg mapping table (characters). Need to adjust class to remove the above error in the function.
