### ISSUE TITLE
run on CI data pack did not pick up community index testing

### ISSUE THREAD

**Issue by gsarfaty** [USAID-OHA-SI/tameDP#2]
Hi! I ran on CI and did not see community index in the output, though it is present in the SNUxIM tab. 

May need to change HTS_INDEX_COMM to HTS_INDEX_COM in the mutate on line 19 of clean_indicators.R?

**Comment by achafetz** [comment]
Dope! That’s exactly it. I’ll update when I get in and push up the new version. Can you email me CI’s DP and I’ll rerun it for you?
