### ISSUE TITLE
Additional Fields request for TameDP Exports

### ISSUE THREAD

**Issue by nmcdavid** [USAID-OHA-SI/tameDP#24]
Hi all,

Would it be possible to add a time stamp and/or file name/last saved field to the TameDP exports. I work with a lot of files that can change multiple times a day and it might a good field to reference for folks who want to know if they are working with the latest version. Possible options include
- Using the TODAY function to print time and date the export was done. This wouldn't speak to the version of the file(s) ran through TameDP but could be a helpful reference
- Using the file name. This is assuming file names are changed/updated when data packs are altered. Methods are different in each country
- Using the file name and "Last Modified" timestamp from the operating system. Thinking through it (for not too long so...yeah) this might be the best option. Not sure how/if this works with files that are checked out on Sharepoint for edits but figured that we'd always have the the same output if the last modified and file name remain the same.

Let me know what you think

**Comment by achafetz** [comment]
Able to add in two new fields, `source_name` and `source_processed`.  Unable to add a last modified - can't seem to extract this out of the Excel file.
